const ADMIN_KEY='callfocus_admin_global_v3';
const PASS_KEY='callfocus_admin_pass_v3';
const VOICES=['alloy','ash','ballad','coral','echo','sage','shimmer','verse','marin','cedar'];
const DEFAULTS={maleVoice:'cedar',femaleVoice:'marin',model:'gpt-realtime-2.1',instructions:'Have a natural live spoken conversation using the supplied context. Do not read system context aloud. Keep replies natural, appropriately brief, emotionally aware and grounded in the facts provided. Never invent personal history, relationship milestones, promises or sensitive facts that were not supplied or established during the current call.',opening:'Start naturally as soon as the call connects. Use the relationship, current topic and both callers’ local times when relevant.',speakFirst:true,interruptions:true};
const $=id=>document.getElementById(id);
const load=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}};
const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
async function hashText(text){const bytes=new TextEncoder().encode(text);const digest=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(digest)].map(b=>b.toString(16).padStart(2,'0')).join('');}
function toast(msg){$('toast').textContent=msg;$('toast').classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>$('toast').classList.add('hidden'),2200)}
function fill(){const current={...DEFAULTS,...load(ADMIN_KEY,{})};const options=VOICES.map(v=>`<option value="${v}">${v}</option>`).join('');$('adminMaleVoice').innerHTML=options;$('adminFemaleVoice').innerHTML=options;$('adminMaleVoice').value=current.maleVoice;$('adminFemaleVoice').value=current.femaleVoice;$('adminModel').value=current.model;$('adminInstructions').value=current.instructions;$('adminOpening').value=current.opening;$('adminSpeakFirst').checked=current.speakFirst!==false;$('adminInterruptions').checked=current.interruptions!==false;}
function showDashboard(){$('adminGate').classList.add('hidden');$('adminDashboard').classList.remove('hidden');fill();}
async function gate(){const stored=localStorage.getItem(PASS_KEY);const entered=$('adminPasscode').value;if(!entered||entered.length<6)return toast('Use at least 6 characters');const hash=await hashText(entered);if(!stored){localStorage.setItem(PASS_KEY,hash);showDashboard();toast('Admin access created');return;}if(hash!==stored)return toast('Incorrect admin passcode');showDashboard();}
$('adminGateBtn').onclick=gate;$('adminPasscode').addEventListener('keydown',e=>{if(e.key==='Enter')gate()});$('adminLockBtn').onclick=()=>{location.reload()};$('saveAdminBtn').onclick=()=>{save(ADMIN_KEY,{maleVoice:$('adminMaleVoice').value,femaleVoice:$('adminFemaleVoice').value,model:$('adminModel').value.trim()||DEFAULTS.model,instructions:$('adminInstructions').value.trim()||DEFAULTS.instructions,opening:$('adminOpening').value.trim()||DEFAULTS.opening,speakFirst:$('adminSpeakFirst').checked,interruptions:$('adminInterruptions').checked});toast('Admin settings saved')};
if(localStorage.getItem(PASS_KEY)){$('adminGateTitle').textContent='Admin sign in';$('adminGateText').textContent='Enter your admin passcode to manage CallFocus system settings.';$('adminGateBtn').textContent='Unlock admin';}
