const ADMIN_KEY='callfocus_admin_global_v4';
const PASS_KEY='callfocus_admin_pass_v4';
const LEGACY_ADMIN_KEY='callfocus_admin_global_v3';
const VOICES=['alloy','ash','ballad','coral','echo','sage','shimmer','verse','marin','cedar'];
const DEFAULTS={maleVoice:'cedar',femaleVoice:'marin',model:'gpt-realtime-2.1',instructions:'Have a natural live spoken conversation using the supplied context. Do not read system context aloud. Keep replies conversational, appropriately brief, emotionally aware and grounded in the facts provided. Never invent personal history, relationship milestones, promises or sensitive facts that were not supplied or established during the current call.',opening:'Begin naturally as soon as the call connects. Use the relationship, current topic and both callers’ local times when relevant.',speakFirst:true,interruptions:true};
const $=id=>document.getElementById(id);
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
async function hashText(text){const bytes=new TextEncoder().encode(text);const digest=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(digest)].map(b=>b.toString(16).padStart(2,'0')).join('')}
function toast(msg){$('toast').textContent=msg;$('toast').classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>$('toast').classList.add('hidden'),2200)}
function current(){return {...DEFAULTS,...read(ADMIN_KEY,read(LEGACY_ADMIN_KEY,{}))}}
function fill(){const c=current();const opts=VOICES.map(v=>`<option value="${v}">${v}</option>`).join('');$('adminMaleVoice').innerHTML=opts;$('adminFemaleVoice').innerHTML=opts;$('adminMaleVoice').value=c.maleVoice;$('adminFemaleVoice').value=c.femaleVoice;$('adminModel').value=c.model;$('adminInstructions').value=c.instructions;$('adminOpening').value=c.opening;$('adminSpeakFirst').checked=c.speakFirst!==false;$('adminInterruptions').checked=c.interruptions!==false}
function showDashboard(){$('adminGate').classList.add('hidden');$('adminDashboard').classList.remove('hidden');fill()}
async function gate(){const stored=localStorage.getItem(PASS_KEY),entered=$('adminPasscode').value;if(!entered||entered.length<6)return toast('Use at least 6 characters');const hash=await hashText(entered);if(!stored){localStorage.setItem(PASS_KEY,hash);showDashboard();toast('Admin access created');return}if(hash!==stored)return toast('Incorrect admin passcode');showDashboard()}
$('adminGateBtn').onclick=gate;$('adminPasscode').addEventListener('keydown',e=>{if(e.key==='Enter')gate()});$('adminLockBtn').onclick=()=>location.reload();$('saveAdminBtn').onclick=()=>{write(ADMIN_KEY,{maleVoice:$('adminMaleVoice').value,femaleVoice:$('adminFemaleVoice').value,model:$('adminModel').value.trim()||DEFAULTS.model,instructions:$('adminInstructions').value.trim()||DEFAULTS.instructions,opening:$('adminOpening').value.trim()||DEFAULTS.opening,speakFirst:$('adminSpeakFirst').checked,interruptions:$('adminInterruptions').checked});toast('Admin settings saved')};
if(localStorage.getItem(PASS_KEY)){$('adminGateTitle').textContent='Admin sign in';$('adminGateText').textContent='Enter your admin passcode to manage CallFocus system settings.';$('adminGateBtn').textContent='Unlock admin'}
